name: Java CI with Maven

on:
  push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set test DB URI
        run: |
          echo "Replacing MongoDB URI in application-test.yml"
          sed -i "s|mongodb://localhost:27017/|$TEST_DB_URI|g" src/test/resources/application-test.yml
          cat src/test/resources/application-test.yml
      - name: Build and test with coverage
        run: mvn verify jacoco:report
      - name: Cache OWASP Dependency Check data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: owasp-${{ runner.os }}
          restore-keys: |
            owasp-${{ runner.os }}
      - name: Security scan
        run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}
